### ISSUE TITLE
how i run it

### ISSUE THREAD

**Issue by vahidalvandi** [samdark/sitemap#1]
hi dear 

i download sitemap and update with composer update command line

i am amator and need help you for run this script 

for example i create index.php and set this code 
////////////////
<?php

if(file_exists('vendor/autoload.php')){
require 'vendor/autoload.php';
}

use samdark\sitemap;

$sitemap = new Sitemap();

// add page
$sitemap->addItem(new SitemapItem(
    'http://rmcreative.ru/', // URL
    time(), // last modifcation timestamp
    Item::DAILY, // update frequency
    0.7 // priority
));

// add more pages
foreach ($pages as $page){
    $sitemap->addItem(new SitemapItem(
        'http://rmcreative.ru/' . $page->url,
        $page->updatedOn,
        Item::MONTHLY
    ));
}

// generate sitemap.xml
$sitemap->writeToFile('sitemap.xml');

// or get it as string
$sitemapString = $sitemap->render();

////////////////////////////////////////////
after run have more error

Fatal error: Class 'samdark\sitemap' not found in C:\xampp\htdocs\samdark\index.php on line 9
how i run it????

**Comment by vahidalvandi** [comment]
update ////////


<?php

 if(file_exists('vendor/autoload.php')){
	require 'vendor/autoload.php';
} 

use  samdark\sitemap;

$sitemap = new Sitemap();

// add page
$sitemap->addItem(new SitemapItem(
    'http://rmcreative.ru/', // URL
    time(), // last modifcation timestamp
    Item::DAILY, // update frequency
    0.7 // priority
));

// add more pages
foreach ($pages as $page){
    $sitemap->addItem(new SitemapItem(
        'http://rmcreative.ru/' . $page->url,
        $page->updatedOn,
        Item::MONTHLY
    ));
}

// generate sitemap.xml
$sitemap->writeToFile('sitemap.xml');

// or get it as string
$sitemapString = $sitemap->render();


//////////

error
Fatal error: Class 'samdark\sitemap' not found in C:\xampp\htdocs\samdark\index.php on line 9

**Comment by vahidalvandi** [comment]
i now correct it


<?php

 
 require 'vendor/autoload.php';
 
use  samdark\sitemap\Sitemap;
use  samdark\sitemap\Item;


$sitemap = new Sitemap();

 
 
 
// add more pages
 
    $sitemap->addItem(new Item(
        'http://rmcreative.ru/' . 'sdfsf.htm',
        '201',
        Item::MONTHLY
    ));
 

// generate sitemap.xml
$sitemap->writeToFile('sitemap.xml');

**Comment by lynicidn** [comment]
https://github.com/samdark/sitemap/pull/2
