### ISSUE TITLE
Support of sitemaps index file 

### ISSUE THREAD

**Issue by smartfin** [samdark/sitemap#12]
Google has support management   multiple sitemap files and allow to submit them as one .
Need to create sitemap.index.xml file with list of sitemap files
Example: 
```
<?xml version="1.0" encoding="UTF-8"?>
   <sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
   <sitemap>
      <loc>http://www.example.com/sitemap1.xml.gz</loc>
      <lastmod>2004-10-01T18:23:17+00:00</lastmod>
   </sitemap>
   <sitemap>
      <loc>http://www.example.com/sitemap2.xml.gz</loc>
      <lastmod>2005-01-01</lastmod>
   </sitemap>
   </sitemapindex>
```

https://support.google.com/webmasters/answer/75712?hl=en

**Comment by samdark** [comment]
It is alreadt supported: https://github.com/samdark/sitemap/blob/master/Index.php. See readme for usage.
