### ISSUE TITLE
Add support of alternate elements

### ISSUE THREAD

**Issue by smartfin** [samdark/sitemap#14]
Google has support of XML Sitemap rel=alternate elements for relationship between web site and mobile app. 

https://developers.google.com/app-indexing/reference/deeplinks?hl=en

**Comment by b1rdex** [comment]
The right link for spec for this: https://developers.google.com/webmasters/mobile-sites/mobile-seo/separate-urls#annotation-in-sitemaps

Also, `alternate` elements are used to indicate multilanguage support for site pages.
