### ISSUE TITLE
Class not found

### ISSUE THREAD

**Issue by nigelterry** [samdark/sitemap#18]
This is more a comment than an issue. I'm using this with Yii2.

I found I need:
use samdark\sitemap\Sitemap;
use samdark\sitemap\Index;

When I used:
use samdark\sitemap

classes Sitemap and Index were not found. Might be a stupid error on my part, but in case others are having the same issue, I thought I'd mention it.

**Comment by samdark** [comment]
Yes, that's PHP namespaces.

**Comment by nigelterry** [comment]
Then I think you need to change README.md where the How To Use it section has:

use samdark\sitemap;

**Comment by samdark** [comment]
https://github.com/samdark/sitemap/commit/fbe46d3745d103dc7ccf01398c65fc9729edcb5a
