### ISSUE TITLE
Use of sitemap

### ISSUE THREAD

**Issue by MarcelVe** [samdark/sitemap#20]
Hi, how to append new items in 'sitemap.xml' after finished.

Sorry, but my english is not so good.
Thanks you.

**Comment by samdark** [comment]
After finished what?

**Comment by MarcelVe** [comment]
Hi, sorry but my english is not so good.

For example:
after the sitemap.xml has been created with items, how to add more items?
In my tests, this sitemap.xml lost the items and the new one is added.

Thank you.

**Comment by samdark** [comment]
You can't you have to re-create it.
