### ISSUE TITLE
Add support for filesystem adapters

### ISSUE THREAD

**Issue by ejunker** [samdark/sitemap#25]
This is based on discussion in #24 where I want to be able to write the sitemaps and index to Amazon S3.

I think a very simple interface like this may work:

``` php
interface FilesystemAdapterInterface
{
    /**
     * Create a file or update if exists.
     *
     * @param string $path     The path to the file.
     * @param string $contents The file contents.
     *
     * @return bool True on success, false on failure.
     */
    public function put($path, $contents);
}
```

And then a FilesystemAdapter could be passed into the constructor and used when writing files.

**Comment by samdark** [comment]
No, it won't. If there are many URLs keeping it all in memory and then writing at once will cause huge memory usage.

**Comment by ejunker** [comment]
Ok, adding an append() method would be useful

```php
interface FilesystemAdapterInterface
{
    /**
     * Create a file or update if exists.
     *
     * @param string $path     The path to the file.
     * @param string $contents The file contents.
     *
     * @return bool True on success, false on failure.
     */
    public function put($path, $contents);

    /**
     * Append content to an existing file.
     *
     * @param string $path     The path to the file.
     * @param string $content The content to append.
     *
     * @return bool True on success, false on failure.
     */
    public function append($path, $content);
}
```

**Comment by samdark** [comment]
How to handle overwriting of existing files?

**Comment by ejunker** [comment]
`put()` is essentially `file_put_contents()` without the `FILE_APPEND` flag set. If path does not exist, the file is created. Otherwise, the existing file is overwritten.

**Comment by samdark** [comment]
OK. Makes sense. @WinterSilence what do you think?

**Comment by WinterSilence** [comment]
@samdark Maybe - need working example or test, 
@ejunker Few changes: 
name: `FilesystemAdapterInterface` to `StorageInterface`,
methods: `put, append` to `write(mixed $data),read()` + add `__construct(array $config = [])`.

Class implemented `StorageInterface` contain all logic to working with data.
`StorageInterface::$config`: 
~~~
$sitemap = new Sitemap(new Storage\File([$filePath = '...', $maxUrls = 1000, $bufferSize = 1000]));
$sitemap = new Sitemap(new Storage\MyCache([$key = '...', $ttl = 3600]));
~~~

**Comment by samdark** [comment]
How to get a list of file names written then?

**Comment by WinterSilence** [comment]
@samdark 
1.Use method `read()` 
2. Add method `getFiles()` for `Storage\File` (alias for `read()`?) 
3. Auto create sitemapindex if `Sitemap::fileCount > 1`

**Comment by samdark** [comment]
That would do, yes.

**Comment by WinterSilence** [comment]
@samdark What's next?

**Comment by samdark** [comment]
If you have extra time to burn you may implement refactoring. Along with https://github.com/samdark/sitemap/tree/refactroring it could be released as a new major version.
