### ISSUE TITLE
Ability to update a sitemap

### ISSUE THREAD

**Issue by websirnik** [samdark/sitemap#29]
It would be useful to have an ability to update a sitemap. The use case is where URLs are being added dynamically. Currently, I can't easily append just one URL to the sitemap.

**Comment by samdark** [comment]
Interesting idea. That would involve either reading existing XML and writing it again or directly appending...

**Comment by WinterSilence** [comment]
@samdark Directly appending - bad idea, because need check duplicates. We can save serialized xml as cache, but I'm think it's should be in the extension of Sitemap.

**Comment by samdark** [comment]
If there are 50K URLs in a map, deserializing it completely into memory is a very bad idea. It basically won't fit.

**Comment by WinterSilence** [comment]
@samdark 
> reading existing XML and writing it again
it's same, I don't see other ways for check url element in sitemap.

**Comment by samdark** [comment]
Considered it and it seems it's not a good idea overall. It's better to re-generate.
