### ISSUE TITLE
Не вышло запустить

### ISSUE THREAD

**Issue by ASYOU99** [samdark/sitemap#40]
Fatal error: Class 'samdark\sitemap\Sitemap' not found
Почитал аналогичные описания у Вас в ветке но так и не понял почему вылазит ошибка: немспейсы стоят корректно, шторм ошибок не показывает. Использовал пример с Вашего описания.

**Comment by erickskrauch** [comment]
Что отвечает за автозагрузку классов?
Что произойдёт, если дописать `\` в начало имени класса, чтобы получилось `samdark\sitemap\Sitemap`?

**Comment by ASYOU99** [comment]
если дописать \  получаем  почти тоже Fatal error: Class 'Sitemap' not found

**Comment by ASYOU99** [comment]
автозагрузка происходит через автолоад который создается при установке этого проекта

**Comment by samdark** [comment]
Composer-ский autoload подключен?

**Comment by ASYOU99** [comment]
ну на сколько понимаю да в папке вендор лежит файл автолоад который указывает на файл автолоада в папке компосера

**Comment by samdark** [comment]
А он подключен у вас?

**Comment by ASYOU99** [comment]
все выяснил проблема была с другой стороны: по непонятной причине глючил openserver (остальные проект тоже выдавали ошибки). Переставил все заработало. Извеняйте за ложную тревогу.
