### ISSUE TITLE
Error when run Composer Require

### ISSUE THREAD

**Issue by Heavywavez** [samdark/sitemap#41]
`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: samdark/sitemap[2.0.0, dev-master].
    - Can only install one of: samdark/sitemap[2.0.1, dev-master].
    - Can only install one of: samdark/sitemap[2.0.2, dev-master].
    - Can only install one of: samdark/sitemap[2.0.3, dev-master].
    - Can only install one of: samdark/sitemap[2.0.4, dev-master].
    - Can only install one of: samdark/sitemap[2.0.5, dev-master].
    - Can only install one of: samdark/sitemap[2.0.6, dev-master].
    - Can only install one of: samdark/sitemap[2.0.7, dev-master].
    - Installation request for samdark/sitemap dev-master -> satisfiable by samdark/sitemap[dev-master].
    - Installation request for samdark/sitemap ^2.0 -> satisfiable by samdark/sitemap[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7].

Installation failed, reverting ./composer.json to its original content.`

**Comment by samdark** [comment]
Hmm... PHP version?

**Comment by samdark** [comment]
Closing since no additional info was given.
