### ISSUE TITLE
How to using a sitemap to indicate alternate language pages

### ISSUE THREAD

**Issue by Chienle** [samdark/sitemap#42]
I have using this composer for my project but I don't know how to add xhtml:link into sitemap, please help me when you have time, thanks a lot!

https://support.google.com/webmasters/answer/2620865?hl=en

**Comment by samdark** [comment]
It seems to be non-standard sitemap and isn't currently supported.

**Comment by Chienle** [comment]
Thank for answer, please see more information from here https://webmasters.googleblog.com/2012/05/multilingual-and-multinational-site.html

**Comment by samdark** [comment]
Duplicate of #14
