### ISSUE TITLE
XMLWriter::writePi()

### ISSUE THREAD

**Issue by duzun** [samdark/sitemap#73]
I need to add an `xml-stylesheet` to the sitemap, but can't access the `$writer`.
Is there a way to add a Pi?

Thanks!

**Comment by samdark** [comment]
Would you please elaborate about what do you want to achieve?

**Comment by duzun** [comment]
Take a Look at This beautiful [sitemap](https://www.similarweb.com/corp/sitemap_index.xml)

**Comment by ParitoshBh** [comment]
I believe https://github.com/samdark/sitemap/pull/63 will address this issue.

**Comment by craftyshaun** [comment]
Closing this as resolved by #63 which was released in 2.3.0
