### ISSUE TITLE
Feature: Auto-submission to search engines

### ISSUE THREAD

**Issue by pionl** [samdark/sitemap#87]
Hi,

while researching packages for building sitemap XMLs I've found this neat feature in this package https://github.com/nilportugues/php-sitemap#block4.1 

I think that would be interesting in this package? (at this moment I dont need it, but if I find the time I could implementing in this package and found out if it works).

Thanks for the package and have a great day,

**Comment by samdark** [comment]
That is interesting but is out of scope of this package.

**Comment by pionl** [comment]
Ok thanks for the info :)
