### ISSUE TITLE
Не работает дозапись при генерации карты сайта

### ISSUE THREAD

**Issue by OsclassEvo** [samdark/sitemap#94]
Смысл в том, что когда приходится генерировать сразу карту сайта большого размера (более 1 млн. строк) приходится делать ее генерацию рекурсией и отдавать вашему скрипту порциями по 25 тыс. строк за раз, чтобы скрипту не приходилось долго ждать ответа от сервака. Так вот при каждой отправке порции строк он тупо перезаписывает файл, а не дополняет его. Нельзя ли доработать так, чтобы скрипт добавлял записи, а не перезаписывал их по новой?

**Comment by samdark** [comment]
Скорее всего вам подойдёт sitemap index + несколько файлов sitemap. См. README.
